### ISSUE TITLE
File Writes

### ISSUE THREAD

**Issue by rphillips** [jslatts/stalker#8]
I am using stalker version 0.0.12. I have custom logic to figure out if a file is done being written to. Does stalker support this yet?

**Comment by jslatts** [comment]
No, currently it will (at least on mac/linux) notify as soon as the inode is created. I am not sure what the behavior on windows would be.

How did you implement your custom logic? Just checking mtime? I would be happy to take a pull request. Otherwise, it is something I can put in the queue to implement.

**Comment by rphillips** [comment]
Yes. I say add it to the queue. I may get to making it more portable, but isn't the priority at the moment. Thanks.

**Comment by jslatts** [comment]
Don't think I will get around to doing this in a bounded future timeframe, but I would accept a patch!
